### ISSUE TITLE
Logs User Claims Recursively

### ISSUE THREAD

**Issue by jmather** [olsh/serilog-sinks-sentry#10]
So I tried wiring this up and got this MASSIVE structure dumped into the logs, as it destructured User, then Claims, then each Claim refs back to the User, then ... whee!

**Comment by olsh** [comment]
Hi @jmather,

Have you added the destructuring policy as described here?
https://github.com/olsh/serilog-sinks-sentry#capturing-httpcontext-aspnet-core

```csharp
.Destructure.With<HttpContextDestructingPolicy>()
```

**Comment by olsh** [comment]
Closing this out due to inactivity, please feel free reopen the issue.
