### ISSUE TITLE
UserFactory is not available

### ISSUE THREAD

**Issue by christianpanton** [olsh/serilog-sinks-sentry#11]
It would be great if the userFactory would be available as a parameter for the sink.

**Comment by olsh** [comment]
Hi @christianpanton,

Thanks for the suggestion 👍 

Do you mean [ISentryUserFactory](https://github.com/getsentry/raven-csharp/blob/952adead4551042b51fa624982a8804ddb8752a6/src/app/SharpRaven/Data/ISentryUserFactory.cs)?

Well, it's pretty easy to expose it.
But I wonder, how are you going to use it?

**Comment by christianpanton** [comment]
In some applications, the current user from the [HttpContext]( https://github.com/olsh/serilog-sinks-sentry/blob/master/src/Serilog.Sinks.Sentry/SentrySink.cs#L68). But for my use case I would like to handle a self-managed user concept, not available on the HttpContext. This enables me to calculate the number of affected user in a much more reliable way.

**Comment by olsh** [comment]
Thanks for the explanation!

The factories parameters will be available in the 2.2.0 version.
