### ISSUE TITLE
Unhandled exception wnen using HttpContextDestructingPolicy

### ISSUE THREAD

**Issue by sashatk** [olsh/serilog-sinks-sentry#12]
When is using .Destructure.With<**HttpContextDestructingPolicy**>() and appear some specific log, e.g _Warning: AcceptLanguageHeaderRequestCultureProvider returned the following unsupported UI Cultures '["en-GB", "en-DE", "en"]'._

Then such exception is caused:

> [ERROR] System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'FileBufferingReadStream'.
>    at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
>    at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.set_Position(Int64 value)
>    at Serilog.AspCoreHttpContextAdapter.DynamicHttpContextRequest..ctor(HttpContext context) in C:\projects\serilog-sinks-sentry\src\Serilog.Sinks.Sentry.AspNetCore\AspCoreHttpContextAdapter.cs:line 76
>    at Serilog.AspCoreHttpContextAdapter.GetRequestBody() in C:\projects\serilog-sinks-sentry\src\Serilog.Sinks.Sentry.AspNetCore\AspCoreHttpContextAdapter.cs:line 48

When is not using HttpContextDestructingPolicy - then all is fine.

Could you please fix it or add some try/catch that this code doesn't throw exception and don't stop the whole pipeline.

Thanks.

**Comment by olsh** [comment]
Hi @sashatk,

Could you please specify the version of the NuGet package?

Thanks.

**Comment by sashatk** [comment]
hi @olsh,

Yes, AddSentryContext is added in Startup.Configure
and is using serilog.sinks.sentry.aspnetcore 2.1.6 in .NET Core 2.0

Yes, try/catch is there - should be fine. When I comment the using of HttpContextDestructingPolicy - then app works fine, but when is using HttpContextDestructingPolicy and is using a culture another than in AcceptLanguageHeaderRequestCultureProvider - then the request fails, but should be only warning(about supported culture) and continuation  of pipeline.

Thanks.

**Comment by sashatk** [comment]
When you setup some culture in your Startup.cs and but your browser sends another culture request, then is generated warning by .NET _Warning: AcceptLanguageHeaderRequestCultureProvider returned the following unsupported UI Cultures '["en-GB", "en-DE", "en"]'._ and when sending this warning to Sentry appear this error.
Example of Startup class that setup culture:
`

public void Configure(IApplicationBuilder app)
{
	app.AddSentryContext();
	
	var supportedCultures = new[]
	{
		new CultureInfo("en-US")
	  , new CultureInfo("de-DE"),
	};
				
	app.UseRequestLocalization(new RequestLocalizationOptions
	{
		DefaultRequestCulture = new RequestCulture("en-US"),
		SupportedCultures = supportedCultures,
		SupportedUICultures = supportedCultures,
	});
}`
And you have setuped before `.Destructure.With<HttpContextDestructingPolicy>()`
Then such error is appeared, could reproduce it again:
`
[11:40:16 WRN] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported UI Cultures '["en-US", "en", "de-DE"]'.
[ERROR] System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.set_Position(Int64 value)
   at Serilog.AspCoreHttpContextAdapter.DynamicHttpContextRequest..ctor(HttpContext context) in C:\projects\serilog-sinks-sentry\src\Serilog.Sinks.Sentry.AspNetCore\AspCoreHttpContextAdapter.cs:line 76
   at Serilog.AspCoreHttpContextAdapter.GetRequestBody() in C:\projects\serilog-sinks-sentry\src\Serilog.Sinks.Sentry.AspNetCore\AspCoreHttpContextAdapter.cs:line 48
`

**Comment by dmitriifilonenko** [comment]
Hi Oleg,

I encountered a similar issue even without any language related stuff.

I use the latest versions of Serilog.Sinks.Sentry and Serilog.Sinks.Sentry.AspNetCore (2.4.1).
Target framework is .NET Core 2.2

When app is configured **with** UseDeveloperExceptionPage() I get the following stack trace:

> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'FileBufferingReadStream'.
>    at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
>    at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.ReadIntoBuffer()
>    at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.Read(Char[] buffer, Int32 index, Int32 count)
>    at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
>    at Newtonsoft.Json.JsonTextReader.ReadNullChar()
>    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
>    at Newtonsoft.Json.JsonTextReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

When I run app **without** UseDeveloperExceptionPage() then I get this stack trace:

> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'FileBufferingReadStream'.
>    at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
>    at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.ReadIntoBuffer()
>    at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.Read(Char[] buffer, Int32 index, Int32 count)
>    at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
>    at Newtonsoft.Json.JsonTextReader.ReadNullChar()
>    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
>    at Newtonsoft.Json.JsonTextReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Serilog.SentrySinkContextMiddleware.Invoke(HttpContext context) in C:\projects\serilog-sinks-sentry\src\Serilog.Sinks.Sentry.AspNetCore\SentrySinkContextMiddleware.cs:line 26

If I remove `Destructure.With<HttpContextDestructingPolicy>()` then it works fine.
Also it helps to turn off logs for Microsoft namespace:

> config.MinimumLevel.Override("Microsoft", LogEventLevel.Fatal)

 (well, not to turn off actually, but to set log level to _"Fatal"_ which in less severe situations works as switch-off effectively).

**Comment by dmitriifilonenko** [comment]
@olsh I think I know why you can't reproduce it.
By default Sentry configuration has `restrictedToMinimumLevel = LogEventLevel.Error`. 
In my solution I configured it with LogEventLevel.Information:
> loggerConfiguration.WriteTo.Sentry(
>                 logsConfig["SentryDsn"],
>                 environment: configuration["ASPNETCORE_ENVIRONMENT"],
>                 **restrictedToMinimumLevel: LogEventLevel.Information**)
>                 .Destructure.With<HttpContextDestructingPolicy>()
>                 .Filter.ByExcluding(e => e.Exception?.CheckIfCaptured() == true);

Loggers in Microsoft.AspNetCore.* use _Information_ level. So if you allow the library to handle such logs you may be able to reproduce the issue, I hope.

Thanks and regards!

**Comment by olsh** [comment]
@dmitriifilonenko thanks for the investigation. 👍 
I'll take a look soon.

**Comment by olsh** [comment]
Updated version Serilog.Sinks.Sentry.AspNetCore 2.4.2 was published.
Please try to update it and let me know if the issue fixed.

Feel free to reopen the issue if the bug still exists.

Thanks.

**Comment by dmitriifilonenko** [comment]
Hi Oleg,

Now everything works fine. Thank you for your efforts!

Regards,
Dmitry
