### ISSUE TITLE
Add support of new Sentry SDK

### ISSUE THREAD

**Issue by chromigo** [olsh/serilog-sinks-sentry#14]
We want to get sink for new SDK https://blog.sentry.io/2018/09/19/new-sdks-unified-python-javascript-dotnet-rust instead of old one https://github.com/getsentry/raven-csharp

here more detail https://github.com/getsentry/sentry-dotnet
https://github.com/getsentry/sentry-dotnet#compatibility

**Comment by olsh** [comment]
It seems like the support will be implemented in the official package
https://github.com/getsentry/sentry-dotnet/pull/118

@bruno-garcia could you please provide more info on this, will you support Serilog integration officially?

**Comment by bruno-garcia** [comment]
@olsh we have a PR there open which I haven't had time to go through in detail and merge.
But so far it does look good and we could merge it in.

This package does target .NET Framework 4.5 which won't be possible through that one.
If we go through in updating this, the support to net45 would need to be dropped.

**Comment by ahmedspiir** [comment]
what about now @olsh  the PR has been merged in November

**Comment by olsh** [comment]
@ahmedspiir 
Well, now we have an official Serilog integration, so I don't see any sense to implement yet another sink for this. 

Let me know if you have any thoughts on this.

**Comment by olsh** [comment]
I'm closing the issue due to inactivity.
Feel free to reopen it if you have suggestions.
