### ISSUE TITLE
Raven Async support

### ISSUE THREAD

**Issue by sashatk** [olsh/serilog-sinks-sentry#15]
Hello, 

could you please add asynchronous sending messaging into Sentry?
Because RavenClient supports  **async** **_ravenClient.CaptureAsync(sentryEvent)_** 
And now your code only support synchronous sending _ravenClient.Capture(sentryEvent);_
Would be nice to have  different Extension methods that support current synchronous operation and asynchronous: e.g . _loggerConfiguration.SentryAsync(sentryConfig.Dns, ... )_

Thank you!

**Comment by chromigo** [comment]
As a workaround I use https://github.com/serilog/serilog-sinks-async. But yes it will be nice to have async sink.

**Comment by chromigo** [comment]
#9 could be connected with this one

**Comment by max-lancaster** [comment]
@sashatk I am using this package together with [serilog-sinks-async](https://github.com/serilog/serilog-sinks-async) which automatically makes all logging calls asynchronous using the standard serilog interface.

**Comment by olsh** [comment]
Duplicate of #9
