### ISSUE TITLE
Support body, header, cookie, etc filtering

### ISSUE THREAD

**Issue by nover** [olsh/serilog-sinks-sentry#16]
We have the need in an application of filtering out parts of the request body, before sending it to Sentry, and I can foresee that we might have the need to filter headers and potentially cookies as well.

Would you accept a PR adding support for user-configurable filtering of said items before sending things down the drain to Serilog and Sentry?

**Comment by olsh** [comment]
Hi @nover 

Yes, I will.
I suppose are you going to use `BeforeSend` function?
https://github.com/getsentry/raven-csharp#debugging-sharpraven

**Comment by nover** [comment]
@olsh Hadn't thought of that one actually. I was thinking more in line of:

```
 app.AddSentryContext(config => {
     config.AddHeaderSanitizing((headers) = headers.Select(...));
     config.AddBodySanitizing((body) => body.Replace("danger danger", string.Empty));
});
```
or something along those lines. 

Also, hooking into SharpRaven directly might be counter productive in terms of issue #14  ?

**Comment by olsh** [comment]
So, this will work only for ASP.NET Core?
We should support legacy MVC as well.

About #14, there is no ETA at the moment, and I'm not sure if it ever will be implemented, because of  https://github.com/getsentry/sentry-dotnet/pull/118

**Comment by nover** [comment]
@olsh I'm a little confused with the requirement for supporting legacy MVC as well - I don't see any packages targeted for asp.net MVC, only for AspNetCore?

**Comment by olsh** [comment]
Hi @nover,

Serilog.Sinks.Sentry.AspNetCore - is a package which adds the integration with ASP NET.Core (HTTP Context capturing).
Serilog.Sinks.Sentry - is a base package which can be used in any .NET app and in classic MVC too. You don't need any configuration for classic MVC, because SharpRaven captures HTTP Context internally.

So, I suggest to add the filter feature to the base package.

**Comment by nover** [comment]
@olsh Gotcha! Totally makes sense :)
