### ISSUE TITLE
Cannot install Serilog.Sinks.Sentry.AspNetCore 2.0.1

### ISSUE THREAD

**Issue by Narcil** [olsh/serilog-sinks-sentry#2]
Hi,

It seems there is an issue with the Core project's csproj. When i try to install the sink to a .Net Core 1.1 project i get : 
Installing Serilog.Sinks.Sentry.AspNetCore 2.0.1.
Package Serilog.Sinks.Sentry.AspNetCore 2.0.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Serilog.Sinks.Sentry.AspNetCore 2.0.1 supports: net451 (.NETFramework,Version=v4.5.1)

I checked the csproj and i think i see the issue :  
line 7 : 

`<TargetFramework>net451</TargetFramework>`

Thanks.
Narcil

**Comment by olsh** [comment]
Hi @Narcil,

This is a [known issue](https://github.com/olsh/serilog-sinks-sentry#known-issues).
The sink doesn't support Core 1.x, because of this issue https://github.com/getsentry/raven-csharp/issues/125

**Comment by Narcil** [comment]
Ok thanks somehow i missed that. The NuGet description is Microsoft.AspNetCore.Http (>= 1.0.0)
