### ISSUE TITLE
how to use tags

### ISSUE THREAD

**Issue by schmitch** [olsh/serilog-sinks-sentry#22]
hello, there is little documentation on how to use tags with this sentry sink.
the original sentry could create tags via the following:
```
  webBuilder.UseSentry((context, options) =>
                    {
                        var demoId = context.Configuration.GetValue<string>("DemoId");
                        if (!string.IsNullOrEmpty(demoId))
                        {
                            options.ConfigureScope(scope =>
                                scope.SetTag("DemoId", demoId));
                        }
                    });
```

and now every log entry had the tag set. this is helpful when somebody needs to identify multiple servers, etc.

**Comment by olsh** [comment]
Hi @schmitch,

The sink has `tags` parameters, which can contain a comma-separated list of tags.
Before sending an event, the sink tries to match Serilog properties with the tags collection, and if there are matches, these properties will be sent as tags.

Here is an example
```csharp
new LoggerConfiguration()
    .WriteTo.Sentry("dsn", tags: "DemoId,UserId")
    .Enrich.WithProperty("DemoId", demoId)

...
// UserId and DemoId will be logged as tags
_log.Error("Something went wrong {UserId}", userId);
```

**Comment by schmitch** [comment]
ok, that's cool. sadly it adds it to "additional data" not sentry tags.

**Comment by olsh** [comment]
Sorry, but I can't reproduce this, here is the full code:
```csharp
int demoId = 5;
Log.Logger = new LoggerConfiguration()
	.WriteTo.Sentry("put_your_dsn_here", tags: "DemoId,UserId")
	.Enrich.WithProperty("DemoId", demoId)
	.CreateLogger();
	
// UserId and DemoId will be logged as tags
var userId = 10;
Log.Logger.Error("Something went wrong {UserId}", userId);
```

Here are the tags
![image](https://user-images.githubusercontent.com/3613592/74675859-99dc9a00-51c5-11ea-8ccb-61ba3ed73291.png)

**Comment by olsh** [comment]
Closed due to inactivity, feel free to reopen the issue.
