### ISSUE TITLE
Serilog properties -> Sentry Tags (Sentry.Serilog)

### ISSUE THREAD

**Issue by Vincent-Balungay-EcoOnline** [olsh/serilog-sinks-sentry#30]
Hi @olsh,

Real nice package, the below feature for setting Tags from Serilog properties works really well.

new LoggerConfiguration()
    .WriteTo.Sentry("dsn", tags: "DemoId,UserId")
    .Enrich.WithProperty("DemoId", demoId)

...
// UserId and DemoId will be logged as tags
_log.Error("Something went wrong {UserId}", userId);

However, this package seem to have been depreciated. So I'm now looking to upgrade to `Sentry.Serilog`, but it seems like there isn't an equivalent feature? or am I missing something?

**Comment by olsh** [comment]
Hi @Vincent-Balungay-EcoOnline 

I don't know if there is such a feature. 
I think, that the new SDK repo is the right place to post your question.

**Comment by Vincent-Balungay-EcoOnline** [comment]
ok thanks, I'll close this one then
