### ISSUE TITLE
Extra parentheses in Tags

### ISSUE THREAD

**Issue by michaldudak** [olsh/serilog-sinks-sentry#7]
When a LogContext has a custom string property (in my case - Request.PathBase), that is included in Tags, the resulting property that's sent to Sentry is wrapped in a pair of unnecessary parens. It messes up the indexing.

I found out that this is due to how tags are serialized: [SentrySink](https://github.com/olsh/serilog-sinks-sentry/blob/master/src/Serilog.Sinks.Sentry/SentrySink.cs#L50) calls `.ToString()` on a Serilog's `ScalarValue` that [adds extra parens](https://github.com/serilog/serilog/blob/32e0c9578db720add74720bceb62bd46967694c4/src/Serilog/Events/ScalarValue.cs#L63).

It seems that the easiest solution would be to pass `"l"` to `.ToString()` but I haven't checked if it'll work in all cases.

**Comment by olsh** [comment]
Thank you for opening the issue!

**Comment by michaldudak** [comment]
Thanks for such a quick response!
