### ISSUE TITLE
Bump SharpRaven to 2.4+

### ISSUE THREAD

**Issue by hulvei3** [olsh/serilog-sinks-sentry#8]
There's a bug in SharpRaven prior to v2.4 where a dsn without a privatekey is making the Ds validation throw. (fixed in v2.4: https://github.com/getsentry/raven-csharp/commit/43b8e4ad9dafc12d7059a568524b12d925d7d989)

Right now, you'll have to manual overwrite the dependency to make a dsn from Sentry work.

**Comment by olsh** [comment]
Thanks, the updated version was pushed to NuGet. 👍
